version: '2'

services:

  vault:
    image: vault:1.12.7
    ports:
      - 8200:8200
    volumes:
      - ./volumes/config:/vault/config
      - ./volumes/file:/vault/file
      - ./volumes/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    entrypoint: vault server -config=/vault/config/vault.json
    cap_add:
      - IPC_LOCK