version: 2.1
jobs:
  build-test-project:
    working_directory: ~/eureka-server
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: maven Build
          command: mvn clean install  
      - run:
            name: run all test
            command: mvn test 
      
 
workflows:
  build-test-deploydockerhub:
    jobs:
    - build-test-project:
        filters:
         branches:
           only:
            - master          
    
    

        